GET http://localhost:5087/users/8
Accept: application/json
Client-Name : REST-Client

###
GET http://localhost:5087/store/5
Accept: application/json

###
GET http://localhost:5087/api/management/apis
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJleHAiOjE3OTE0NDk0MzgsImlzcyI6IkFwaUdhdGV3YXlQbGF0Zm9ybSIsImF1ZCI6IkFwaUdhdGV3YXlDbGllbnRzIn0.CwDLP-1MklioPlCRiBZO_vFvtr8Rq315OPivB2We04g
###
POST http://localhost:5087/api/management/apis
Content-Type: application/json

{
    "Name" :"Orders Management API",
    "RoutePrefix":"/order",
    "DownstreamPath":"/api/order",
    "DestinationAddress":"http://localhost:5297/"
}

###
GET http://localhost:5087/api/management/apis/0

### 
PUT http://localhost:5087/api/management/apis/7
Content-Type: application/json

{
    "Name" :"Orders Management API",
    "RoutePrefix":"/store",
    "DownstreamPath":"/api/order",
    "DestinationAddress":"http://localhost:5297/"
}

###

DELETE  http://localhost:5087/api/management/apis/2
###
POST  http://localhost:5087/api/auth/login
Content-Type: application/json

{
    "Username":"admin",
    "Role":"admin"
}