GET http://localhost:5087/users/8
Accept: application/json
Client-Name : REST-Client

###
GET http://localhost:5087/store/5
Accept: application/json

###
GET http://localhost:5087/api/management/apis

###
POST http://localhost:5087/api/management/apis
Content-Type: application/json

{
    "Name" :"Orders Management API",
    "RoutePrefix":"/order",
    "DownstreamPath":"/api/order",
    "DestinationAddress":"http://localhost:5297/"
}

###
GET http://localhost:5087/api/management/apis/0

### 
PUT http://localhost:5087/api/management/apis/7
Content-Type: application/json

{
    "Name" :"Orders Management API",
    "RoutePrefix":"/store",
    "DownstreamPath":"/api/order",
    "DestinationAddress":"http://localhost:5297/"
}

###

DELETE  http://localhost:5087/api/management/apis/2
###
POST  http://localhost:5087/api/auth/login
Content-Type: application/json

{
    "Username":"admin",
    "Role":"admin"
}